### ISSUE TITLE
Error while installing in V2.91.0

### ISSUE THREAD

**Issue by shibumenon** [doakey3/VSE_Transform_Tools#29]
I get this error when installing VSE 

Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender\2.91\2.91\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VSE_Transform_Tools\__init__.py", line 451, in register
    register_class(cls)
ValueError: register_class(...): already registered as a subclass 'PREV_OT_set_cursor_2d'

**Comment by MoralCode** [comment]
this seems to be the same as the issue posted in #31
