### ISSUE TITLE
Error when i try to enable the addon

### ISSUE THREAD

**Issue by SalvadorGV** [doakey3/VSE_Transform_Tools#34]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gscatter\libmanager\t3dn.py", line 595, in _packer_import
    return _orig_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'VSE_Transform_Tools-1'

**Comment by tin2tin** [comment]
You'll need to use this fork for 2.93: https://github.com/zeograd/VSE_Transform_Tools

**Comment by SalvadorGV** [comment]
thanks! all fine!!!
